name: CI/CD Customer Service

on:
  push:
    branches: [ "main" ]
    # Le pipeline ne se lance QUE si on touche à ce dossier précis
    paths:
      - 'back_end/customer-service/**'
      - '.github/workflows/customer-service.yml'
  workflow_dispatch: # Permet de lancer manuellement pour tester

jobs:
  build-and-secure:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer tout le projet (back_end et front_end)
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Installer Java 21 (Vital pour ton erreur précédente)
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # 3. Compiler avec Maven
      # IMPORTANT : working-directory force la commande à s'exécuter dans le sous-dossier
      - name: Build with Maven
        run: mvn clean package -DskipTests=false
        working-directory: ./back_end/customer-service

      # 4. Scan de sécurité des fichiers (Code & Dépendances)
      - name: Run Trivy vulnerability scanner (Filesystem)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: './back_end/customer-service'
          format: 'table'
          severity: 'CRITICAL,HIGH'

      # 5. Se connecter à Docker Hub (Besoin des Secrets configurés dans GitHub)
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 6. Créer et Envoyer l'image Docker
      # Context : On dit à Docker "Tout se passe dans le dossier back_end/customer-service"
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./back_end/customer-service
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/customer-service:latest

      # 7. Scan de sécurité de l'image finale
      - name: Run Trivy vulnerability scanner (Image)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKER_USERNAME }}/customer-service:latest'
          format: 'table'
          severity: 'CRITICAL,HIGH'