name: CI/CD Customer Service

on:
  push:
    branches: [ "main" ]
    paths:
      - 'back_end/customer-service/**'
      - '.github/workflows/customer-service.yml'
  workflow_dispatch:

jobs:
  build-and-secure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # CORRECTION 1 : J'ai mis le bon nom (JDK 17) pour être cohérent
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # CORRECTION 2 : J'ai enlevé "=false". Maintenant ça ignore vraiment les tests.
      - name: Build with Maven
        run: mvn clean package -DskipTests
        working-directory: ./back_end/customer-service

      - name: Run Trivy vulnerability scanner (Filesystem)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: './back_end/customer-service'
          format: 'table'
          severity: 'CRITICAL,HIGH'

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./back_end/customer-service
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/customer-service:latest

      - name: Run Trivy vulnerability scanner (Image)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.DOCKER_USERNAME }}/customer-service:latest'
          format: 'table'
          severity: 'CRITICAL,HIGH'