name: DevSecOps Customer Service

on:
  push:
    branches: [ "main" ]
    paths:
      - 'back_end/customer-service/**'
      - '.github/workflows/customer-service.yml'
  workflow_dispatch:

jobs:
  build-and-secure:
    runs-on: ubuntu-latest

    steps:
      # 1. On récupère le code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. On installe Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # 3. SCAN DE SÉCURITÉ (Code & Dépendances) - DevSecOps
      # Il vérifie si vos librairies ont des failles avant de compiler
      - name: Security Scan - Code
        uses: aquasecurity/trivy-action@0.16.1
        with:
          scan-type: 'fs'
          scan-ref: './back_end/customer-service'
          format: 'table'
          severity: 'CRITICAL'
          # exit-code: 1 ferait échouer le pipeline.
          # On met 0 pour l'instant pour voir le résultat sans bloquer.
          exit-code: 0

      # 4. Compilation
      - name: Build with Maven
        working-directory: ./back_end/customer-service
        run: mvn clean package -DskipTests

      # 5. Connexion Docker Hub (Utilise le token de votre binôme)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: rahilisalma93
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 6. Construction et Envoi de l'image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./back_end/customer-service
          file: ./back_end/customer-service/Dockerfile
          push: true
          tags: rahilisalma93/customer-service:latest

      # 7. SCAN DE SÉCURITÉ (Image Docker) - DevSecOps
      # Il vérifie l'image finale
      - name: Security Scan - Image
        uses: aquasecurity/trivy-action@0.16.1
        with:
          image-ref: 'rahilisalma93/customer-service:latest'
          format: 'table'
          severity: 'CRITICAL'
          exit-code: 0 # On ne bloque pas pour l'instant