name: CI/CD Customer Service

on:
  push:
    branches: [ "main" ]
    paths:
      - 'back_end/customer-service/**'
      - '.github/workflows/customer-service.yml'
  workflow_dispatch:

jobs:
  build-and-secure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        working-directory: ./back_end/customer-service
        run: mvn clean package -DskipTests

      # Scan de sécurité des fichiers (Optionnel, peut être retiré si bloque)
      - name: Run Trivy vulnerability scanner (Filesystem)
        uses: aquasecurity/trivy-action@0.16.1
        with:
          scan-type: 'fs'
          scan-ref: './back_end/customer-service'
          format: 'table'
          severity: 'CRITICAL,HIGH'

      # Connexion à Docker Hub (Version v3)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: 'rahilisalma93'
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Construction et envoi (Version v5)
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./back_end/customer-service
          file: ./back_end/customer-service/Dockerfile
          push: true
          tags: rahilisalma93/customer-service:latest

      # Scan de l'image (Optionnel)
      - name: Run Trivy vulnerability scanner (Image)
        uses: aquasecurity/trivy-action@0.16.1
        with:
          image-ref: 'rahilisalma93/customer-service:latest'
          format: 'table'
          severity: 'CRITICAL,HIGH'