name: CI/CD Customer Service

on:
  push:
    branches: [ "main" ]
    paths:
      - 'back_end/customer-service/**'
      - '.github/workflows/customer-service.yml'
  workflow_dispatch:

jobs:
  build-and-secure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        working-directory: ./back_end/customer-service
        run: mvn clean package -DskipTests

      # Scan de sécurité des fichiers
      - name: Run Trivy vulnerability scanner (Filesystem)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: './back_end/customer-service'
          format: 'table'
          severity: 'CRITICAL,HIGH'

      # Connexion à Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          # On peut mettre le pseudo en clair ici si on veut
          username: rahilisalma93
          # MAIS le mot de passe doit rester un secret pour la sécurité !
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Construction et envoi de l'image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./back_end/customer-service
          push: true
          # Utilisation de votre pseudo en dur ici aussi
          tags: rahilisalma93/customer-service:latest

      # Scan de l'image Docker générée
      - name: Run Trivy vulnerability scanner (Image)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'rahilisalma93/customer-service:latest'
          format: 'table'
          severity: 'CRITICAL,HIGH'